# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cmpe202App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'AFNetworking', '~> 3.0'
  pod 'CircleBar'
  pod 'CollectionViewPagingLayout'
  # Pods for cmpe202App

  target 'cmpe202AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cmpe202AppUITests' do
    # Pods for testing
  end

end
